image: openjdk:8

before_script:
  - apt-get -qq update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq mysql-server 
  - apt-get install -y -qq maven
  - /etc/init.d/mysql restart
  - mysql -hlocalhost -P3306 -uroot -e"CREATE DATABASE batch_test"
  - mysql -hlocalhost -P3306 -uroot -e"CREATE USER 'batch'@'localhost' IDENTIFIED BY 'batch'"
  - mysql -hlocalhost -P3306 -uroot -e"GRANT ALL ON batch_test.* TO 'batch'@'localhost'"
  
test:
  script:
    - mvn --batch-mode test

#build:
#  script:
#    - mvn clean package -Dmaven.test.skip=true