spring:
    jpa:
        hibernate.ddl-auto: none
        use-new-id-generator-mappings: true
    datasource:
        url: 'jdbc:mysql://localhost:3306/batch'
        username: 'batch'  
        password: 'batch'
    thymeleaf:
        mode: LEGACYHTML5  
        cache: false  
    batch:
        job.enabled: false
        initializer.enabled: true
      